<?xml version="1.0" encoding="UTF-8"?><testrun name="PagamentoTest" project="webpizzaria" tests="10" started="10" failures="0" errors="2" ignored="0">
  <testsuite name="unitario.PagamentoTest" time="0.008">
    <testcase name="testDefinirValorRecebido" classname="unitario.PagamentoTest" time="0.004">
      <error>java.lang.Error: Unresolved compilation problem: 
	The method validarValorRecebido(EnumFormaDePagamento, Float) in the type Pagamento is not applicable for the arguments (Float)

	at dominio.Pagamento.definirValorRecebido(Pagamento.java:70)
	at unitario.PagamentoTest.testDefinirValorRecebido(PagamentoTest.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

</error>
    </testcase>
    <testcase name="testDefinirFormaDePagamentoInvalida" classname="unitario.PagamentoTest" time="0.0"/>
    <testcase name="testCalcularTrocoFormaDePagamentoInvalida" classname="unitario.PagamentoTest" time="0.001"/>
    <testcase name="testDefinirValorRecebidoInvalido" classname="unitario.PagamentoTest" time="0.0">
      <error>java.lang.Exception: Unexpected exception, expected&lt;excecoes.ExcecaoDePagamento&gt; but was&lt;java.lang.Error&gt;
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.Error: Unresolved compilation problem: 
	The method validarValorRecebido(EnumFormaDePagamento, Float) in the type Pagamento is not applicable for the arguments (Float)

	at dominio.Pagamento.definirValorRecebido(Pagamento.java:70)
	at unitario.PagamentoTest.testDefinirValorRecebidoInvalido(PagamentoTest.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	... 15 more

</error>
    </testcase>
    <testcase name="testNovoPagamentoFormaDePagamentoInvalida" classname="unitario.PagamentoTest" time="0.001"/>
    <testcase name="testDefinirFormaDePagamento" classname="unitario.PagamentoTest" time="0.0"/>
    <testcase name="testCalcularTrocoInvalido" classname="unitario.PagamentoTest" time="0.0"/>
    <testcase name="testCalcularTroco" classname="unitario.PagamentoTest" time="0.0"/>
    <testcase name="testNovoPagamentoValorRecebidoInvalido" classname="unitario.PagamentoTest" time="0.0"/>
    <testcase name="testNovoPagamento" classname="unitario.PagamentoTest" time="0.001"/>
  </testsuite>
</testrun>
